"use client";

import { usePathname } from "next/navigation";
import { useEffect, useRef } from "react";

const DEFAULT_TITLE = "Anirudha Kapileshwari - Software Engineer";
const HIDDEN_TITLE = "hey!! click here";

export default function TabTitleWatcher() {
  const pathname = usePathname();
  const visibleTitleRef = useRef(DEFAULT_TITLE);

  useEffect(() => {
    const syncVisibleTitle = () => {
      // Preserve the real, route-specific title generated by Next metadata.
      visibleTitleRef.current = document.title || DEFAULT_TITLE;
    };

    const handleVisibilityChange = () => {
      document.title = document.hidden ? HIDDEN_TITLE : visibleTitleRef.current;
    };

    const raf = window.requestAnimationFrame(() => {
      syncVisibleTitle();
      handleVisibilityChange();
    });

    const titleNode = document.querySelector("title");
    const titleObserver = new MutationObserver(() => {
      if (!document.hidden) {
        syncVisibleTitle();
      }
    });

    if (titleNode) {
      titleObserver.observe(titleNode, { childList: true });
    }

    document.addEventListener("visibilitychange", handleVisibilityChange);

    return () => {
      window.cancelAnimationFrame(raf);
      titleObserver.disconnect();
      document.removeEventListener("visibilitychange", handleVisibilityChange);
      if (!document.hidden) {
        document.title = visibleTitleRef.current;
      }
    };
  }, [pathname]);

  return null;
}
